apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mvc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-mvc-demo
  template:
    metadata:
      labels:
        app: springboot-mvc-demo
    spec:
      containers:
        - name: springboot-mvc-demo
          image: springboot-mvc-demo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-mvc-demo
spec:
  selector:
    app: springboot-mvc-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
