apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mvc-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-mvc-demo
  template:
    metadata:
      labels:
        app: springboot-mvc-demo
    spec:
      containers:
        - name: springboot-mvc-demo
          image: springboot-mvc-demo:latest
          imagePullPolicy: Never       # 👈 ADD THIS LINE
          ports:
            - containerPort: 9090
